### ISSUE TITLE
React server render flicker on Heroku

### ISSUE THREAD

**Issue by hhlevnjak** [Hashnode/mern-starter#226]
Hi,

I'm trying to use the mern-starter configuration. I deployed it to Heroku, bundled the code, and set it to run as production.

The problem is, once on Heroku, I see the flicker as if the page is first rendered on the server side without any styling or images. I've seen that issue here when running in development mode. When I run it locally with the same command as production, like on Heroku, it renders as it should.

Has anyone else had that problem? What am I missing? Either I'm not setting something correctly, or there is a problem with running it on Heroku.

Tnx in advance.

**Comment by ochervak** [comment]
I'm see FOUC on localhost when running `npm run bs`.
What i'm doing wrong ?

**Comment by hakonhk** [comment]
I experience the same behaviour. The server responds with all the right stuff it seems, CSS, HTML and __INITIAL_STATE etc. However, nothing is styled correctly, and I am assuming the HTML and CSS classnames are changed as soon as the app.js script is loaded, and then re-renders the DOM.

Live test can be seen here:
https://vhlive.kroghweb.no/veggli

**Comment by hakonhk** [comment]
This looks like the same issue as [https://github.com/Hashnode/mern-starter/issues/241](url). By applying the fix, I see no more unstyled content.

There is, however, a flicker when the app js is loaded, and the DOM is re-rendered by React.

**Comment by hhlevnjak** [comment]
Tnx, It does seem like it solved the FOUC problem.

I'll close this issue then, as it is now resolved.

**Comment by donedgardo** [comment]
Is the flicker issue still happening, my page flickers on first load. and it running locally in production :/
